name: Build & Deploy to Cloudflare worker

on:
  push:
    branches:
      - cicd
  repository_dispatch:

env:
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CF_GLOBAL_API: ${{ secrets.CF_GLOBAL_API }}
  CF_WORKER_NAME: ${{ secrets.CF_WORKER_NAME }} # Must be lower case
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  JWT_WHITE_LIST: ${{ secrets.JWT_WHITE_LIST }} # No space between commas. No https/http

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:

      # -- Check if environment variables are empty
      - name: Check secret phases
        id: checksecrets
        shell: bash
        run: |
          if [ "$CF_EMAIL" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi
          if [ "$CF_GLOBAL_API" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi
          if [ "$CF_WORKER_NAME" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi
          if [ "$CF_ACCOUNT_ID" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi
          if [ "$JWT_WHITE_LIST" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi

      # -- Rebase to root and setup to use yarn
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # -- Prepare variables
      - name: Prepare variables
        working-directory: ./worker
        run: |
          git config --global url."https://".insteadOf git://
          yarn install && bash create-db.sh $CF_WORKER_NAME $CF_ACCOUNT_ID $CF_EMAIL $CF_GLOBAL_API $JWT_WHITE_LIST && cat ./wrangler.toml

      # -- Build the front-end app
      - name: Build App
        working-directory: ./app
        run: cp .env.example .env && yarn install && yarn prepare && ls && cat .env && cat vite.config.js

      # -- Build the CloudFlare worker
      - name: Build Worker
        working-directory: ./worker
        run: cat wrangler.toml && CF_EMAIL=$CF_EMAIL CF_API_KEY=$CF_GLOBAL_API yarn wrangler publish
